### ISSUE TITLE
Setting environment vars results in corrupt DB on OS X

### ISSUE THREAD

**Issue by thevoiceless** [Pixplicity/humpty-dumpty-android#4]
See 0f7a570156f4982f01b4a0dc88ccde0d6a39b8e6

Setting the `LC_CTYPE` and `LANG` environment variables does allow the script to pull the database on OS X, but it appears to be corrupted. I'm unable to open the file using https://addons.mozilla.org/en-us/firefox/addon/sqlite-manager/

> SQLiteManager: Error in opening file cablevision.db - either the file is encrypted or corrupt
> Exception Name: NS_ERROR_FILE_CORRUPTED
> Exception Message: Component returned failure code: 0x8052000b (NS_ERROR_FILE_CORRUPTED) [mozIStorageService.openUnsharedDatabase]

Commenting-out lines 4 and 5 fixes the issue by making the script fall back to copying the file to the sd card.

**Comment by pflammertsma** [comment]
If you have a change to compare the resulting file against the good one, I'd be eager to learn what's going wrong here. Still a bit perplexed as to why replacing CRLF with LF is causing us so much woes. Perhaps our assumption is wrong and the line feeds should remain?

**Comment by thevoiceless** [comment]
How should I compare them? There are (unsurprisingly) binary differences, but that's about all I can tell.

**Comment by pflammertsma** [comment]
Good question. I'm a bit stumped here.

I'll first take a look with a colleague on OS X this Monday.

**Comment by thevoiceless** [comment]
Any luck?

**Comment by mlagerberg** [comment]
I've tried 8 different `sed` and other commands to strip the carriage returns from the `cat` output. All of them produce invalid database files. I'm stumped.

Any reason not to skip the `sed` method altogether on Mac and always use the copy-to-sd method instead?

**Comment by pflammertsma** [comment]
Unfortunate, I was hoping for a universal solution. The only reason for
trying to avoid SD is the (unlikely) scenario that the external storage is
completely full. In general I'm leaning towards going for the external
storage solution as converting line endings in the first place is rather
odd.

It should be said that we should locate the external storage directory in a
more elegant fashion as `/sdcard/` is deprecated.

One last shot for line endings, although I'm not sure `perl` is installed
by default:

```
perl -pi -e 's/\r\n/\n/g'
```

(From: http://stackoverflow.com/a/14155400/154306)

**Comment by mlagerberg** [comment]
Works like a charm! I've [commited a fix](https://github.com/Pixplicity/humpty-dumpty-android/commit/14cd44499a500aaf08fa7082180cb156975d0fd0) that uses perl on Mac and  `sed` on other platforms.

I'll create a separate issue for changing `/sdcard/` to something else.
