### ISSUE TITLE
Encrypted database returned

### ISSUE THREAD

**Issue by pansardinicolas** [Pixplicity/humpty-dumpty-android#9]
I miswrote the package name and the script returned successfully with an encrypted database. This could get checked.

**Comment by pflammertsma** [comment]
It seems that the output correction that's being applied for some devices
is corrupting it for yours.

Which device are you testing on? Which adb command do you execute to do it
manually?

**Comment by pansardinicolas** [comment]
Actually, as mentioned in the last comment of this issue, I already found
what was happening.
It was only the path to the database which was wrong, btw it didn't
returned any exception.

On 14 June 2016 at 14:50, Paul Lammertsma notifications@github.com wrote:

> It seems that the output correction that's being applied for some devices
> is corrupting it for yours.
> 
> Which device are you testing on? Which adb command do you execute to do it
> manually?
> 
> On Tue, Jun 14, 2016, 17:46 pansardinicolas notifications@github.com
> wrote:
> 
> > The script worked successfully but when I tried to perform "selects" or
> > ".schema"/".tables" commands the sqlite returns "Error: file is encrypted
> > or is not a database".
> > I already made sure it is not caused by permission. Dumping manually
> > without the script works fine.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/Pixplicity/humpty-dumpty-android/issues/9, or mute
> > the thread
> > <
> > https://github.com/notifications/unsubscribe/AARdY_Rqa_f_hMAE-CsO36RO3Jv439p7ks5qLszdgaJpZM4I1eBh
> > 
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Pixplicity/humpty-dumpty-android/issues/9#issuecomment-225961415,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADUiFC2scrUlOsGplBb3qc9OOgTDE6oaks5qLuoAgaJpZM4I1eBh
> .

## 

Nicolas Pansardi
Graduando em Informática Biomédica
Undergraduate B.sc. in Biomedical Informatics
Department of Informatics
_Universidade Federal do Paraná- UFPR_
